"""add post status

Revision ID: 7b36926e160f
Revises: d3eb7cc252ea
Create Date: 2025-12-18 18:08:04.350240

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b36926e160f'
down_revision = 'd3eb7cc252ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=True))

    op.execute("UPDATE posts SET status = 'PUBLISHED' WHERE status IS NULL")

    with op.batch_alter_table('posts', schema=None) as batch_op:
        #Enforce NOT NULL
        batch_op.alter_column(
            'status',
            nullable=False
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###
